[package]
name = "seqkit"
kind = "tool"
version = "2.14.0"
release = 1
license = "Apache-2.0"
main = "src/main.taf"

[repository]
url = "https://github.com/taffish/seqkit"

[command]
name = "taf-seqkit"

[runtime]
pipe = true
command_mode = true

[container]
image = "ghcr.io/taffish/seqkit:2.14.0-r1"
dockerfile = "docker/Dockerfile"
build_platforms = "linux/amd64,linux/arm64"

[meta]
domain = "bio"
categories = ["fasta", "fastq", "sequence-processing", "quality-control", "alignment-processing"]
keywords = ["SeqKit", "FASTA", "FASTQ", "BAM", "gzip", "xz", "zstd", "bzip2", "lz4", "statistics", "subsequence", "sampling", "format-conversion"]
description = "SeqKit ultrafast toolkit for FASTA/Q sequence manipulation and lightweight BAM monitoring."

[upstream]
name = "SeqKit"
type = "github"
repo = "shenwei356/seqkit"
homepage = "https://bioinf.shenwei.me/seqkit/"
manual = "https://bioinf.shenwei.me/seqkit/usage/"
release_url = "https://github.com/shenwei356/seqkit/releases/tag/v2.14.0"
downloads = "https://github.com/shenwei356/seqkit/releases/download/v2.14.0/seqkit_linux_amd64.tar.gz; https://github.com/shenwei356/seqkit/releases/download/v2.14.0/seqkit_linux_arm64.tar.gz"
version = "2.14.0"
license = "MIT"
citation = "Shen, Sipos and Zhao 2024; Shen et al. 2016"
doi = "10.1002/imt2.191; 10.1371/journal.pone.0163962"
pmid = "27706213"
watch = "tags"
strip_prefix = "v"

[smoke]
backend = "docker"
timeout = 120
exist = ["seqkit", "sh", "bash", "grep", "awk", "cut", "cmp", "cp", "mktemp", "tail", "ldd", "rm", "mkdir"]
test = ["sh /opt/seqkit/share/smoke.sh identity", "sh /opt/seqkit/share/smoke.sh basic", "sh /opt/seqkit/share/smoke.sh search", "sh /opt/seqkit/share/smoke.sh convert", "sh /opt/seqkit/share/smoke.sh compression", "sh /opt/seqkit/share/smoke.sh delta", "sh /opt/seqkit/share/smoke.sh replace", "sh /opt/seqkit/share/smoke.sh monitor", "sh /opt/seqkit/share/smoke.sh bam"]
